easy_admin:
    entities:
        Address:
            class: App\Entity\Address
            form:
                fields:
                    - { property: 'country' }
                    - { property: 'city' }
                    - { property: 'zipCode' }
                    - { property: 'addressLines' }

            list:
                fields:
                    - { property: 'country' }
                    - { property: 'city' }
                    - { property: 'zipCode' }
                    - { property: 'addressLines' }
