easy_admin:
    entities:
        Address:
            class: App\Entity\Address
            form:
                fields:
                    - { property: 'country' }
                    - { property: 'city' }
            
            list:
                fields:
                    - { property: 'country' }
                    - { property: 'city' }
