easy_admin:
    entities:
          Wine:
            class: App\Entity\Wine
            form:
                fields:
                    - { property: 'producer' }
                    - { property: 'designation'}
                    - { property: 'color' }
                    - { property: 'variety' }

            list:
                fields:
                    - { property: 'producer' }
                    - { property: 'designation' }

