easy_admin:
    entities:
          Winery:
            class: App\Entity\Winery
            form:
                fields:
                    - { property: 'name' }
                    - { property: 'phone' }
                    - { type: 'group', label: 'Address', icon: 'map-marker-alt', css_class: 'col-sm-4' }
                    - { property: 'address' , type: 'App\Form\AddressType', type_options: {label: false}}

            list:
                fields:
                    - { property: 'name' }

